### ISSUE TITLE
Python27 example error on Ubuntu

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/modelica-buildings#453]
Hi,

for example ```Buildings.Utilities.IO.Python27.Examples.KalmanFilter``` I get the following error:

```
/opt/dymola-2016/source/matrixop.c: In function Integer2String:
/opt/dymola-2016/source/matrixop.c:3549:2: warning: format %ld expects argument of type long int, but argument 5 has type Integer [-Wformat=]
  sprintf(buf,"%*.*ld",(int)minwidth,(int)precision,(int)x);
  ^
/opt/dymola-2016/source/matrixop.c: In function Integer2String2:
/opt/dymola-2016/source/matrixop.c:3570:2: warning: format %ld expects argument of type long int, but argument 4 has type Integer [-Wformat=]
  sprintf(buf,leftJustified?"%-*ld":"%*ld",(int)minwidth,(int)x);
  ^
/opt/dymola-2016/source/matrixop.c:3570:2: warning: format %ld expects argument of type long int, but argument 4 has type Integer [-Wformat=]
In file included from /opt/dymola-2016/source/matrixop.c:3716:0:
/opt/dymola-2016/source/localeless.cpp: In function sscanfCx2_underscore:
/opt/dymola-2016/source/localeless.cpp:308:2: warning: format %lx expects argument of type long unsigned int *, but argument 3 has type unsigned int * [-Wformat=]
  return sscanf(line, "%lx_%lx", a,b);
  ^
/opt/dymola-2016/source/localeless.cpp:308:2: warning: format %lx expects argument of type long unsigned int *, but argument 4 has type unsigned int * [-Wformat=]
/opt/dymola-2016/source/localeless.cpp: In function sscanfClu:
/opt/dymola-2016/source/localeless.cpp:319:2: warning: format %lu expects argument of type long unsigned int *, but argument 3 has type unsigned int * [-Wformat=]
  return sscanf(line, "%lu", a);
  ^
/usr/bin/ld:/media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32/libpython2.7.so: file format not recognized; treating as linker script
/usr/bin/ld:/media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32/libpython2.7.so:1: syntax error
collect2: error: ld returned 1 exit status
```

my path settings are:
```
ubuntu:~$ echo $PYTHONPATH
:/media/psf/Home/Documents/Werkmap/Solarwind/Resources/Python-Sources:/media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Python-Sources
ubuntu:~$ echo $LD_LIBRARY_PATH
:/media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32 
```
I'm using dymola 2016 64 bit on ubuntu 14.04 64 bit.

How can I fix this?

**Comment by mwetter** [comment]
Please verify that you have in `~/.dynasim/setup.mo` the entry
```
Advanced.CompileWith64=1;
```
This will cause a 32 bit compilation. Maybe this is why you get
```
.../Buildings/Resources/Library/linux32/libpython2.7.so: file format not recognized; treating as linker script
```
I verified on my installation and the example works if I execute
```
Buildings$ export PYTHONPATH=${PYTHONPATH}:`pwd`/Resources/Python-Sources
Buildings$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:`pwd`/Resources/Library/linux32
Buildings$ dymola package.mo &
```
I also use  dymola 2016 64 bit on ubuntu 14.04 64 bit

**Comment by Mathadon** [comment]
Thanks for looking into it!

Issue solved, some debug steps that may be relevant for someone else. Solution is below.
### Debug steps:
Setup.mo seems to be automatically generated on my PC so I tested by setting `Advanced.CompileWith64=1;` in the Dymola command window.

I checked the flags that are passed to `dsbuild.sh` and in both cases `Advanced.CompileWith64=0;` or `Advanced.CompileWith64=1;` I only get the flags 


```
-I /media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/C-Sources
-L /media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32
-l ModelicaBuildingsPython2.7
-l python2.7
```
so the option does not seem to do anything. 

I also forced 64 bit mode by changing `dsbuild.sh`.

Then I get:
```
/opt/dymola-2016/source/matrixop.c: In function Integer2String:
/opt/dymola-2016/source/matrixop.c:3549:2: warning: format %ld expects argument of type long int, but argument 5 has type Integer [-Wformat=]
  sprintf(buf,"%*.*ld",(int)minwidth,(int)precision,(int)x);
  ^
/opt/dymola-2016/source/matrixop.c: In function Integer2String2:
/opt/dymola-2016/source/matrixop.c:3570:2: warning: format %ld expects argument of type long int, but argument 4 has type Integer [-Wformat=]
  sprintf(buf,leftJustified?"%-*ld":"%*ld",(int)minwidth,(int)x);
  ^
/opt/dymola-2016/source/matrixop.c:3570:2: warning: format %ld expects argument of type long int, but argument 4 has type Integer [-Wformat=]
In file included from /opt/dymola-2016/source/matrixop.c:3716:0:
/opt/dymola-2016/source/localeless.cpp: In function sscanfCx2_underscore:
/opt/dymola-2016/source/localeless.cpp:308:2: warning: format %lx expects argument of type long unsigned int *, but argument 3 has type unsigned int * [-Wformat=]
  return sscanf(line, "%lx_%lx", a,b);
  ^
/opt/dymola-2016/source/localeless.cpp:308:2: warning: format %lx expects argument of type long unsigned int *, but argument 4 has type unsigned int * [-Wformat=]
/opt/dymola-2016/source/localeless.cpp: In function sscanfClu:
/opt/dymola-2016/source/localeless.cpp:319:2: warning: format %lu expects argument of type long unsigned int *, but argument 3 has type unsigned int * [-Wformat=]
  return sscanf(line, "%lu", a);
  ^
/opt/dymola-2016/source/localeless.cpp: In function fscanfC_Bracket_255s:
/opt/dymola-2016/source/localeless.cpp:147:8: warning: ignoring return value of fscanf, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(f, "%[^\\[]255s", s);
        ^
/usr/bin/ld: skipping incompatible /media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32/libModelicaBuildingsPython2.7.so when searching for -lModelicaBuildingsPython2.7
/usr/bin/ld: cannot find -lModelicaBuildingsPython2.7
/usr/bin/ld: skipping incompatible /media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32/libpython2.7.so when searching for -lpython2.7
collect2: error: ld returned 1 exit status
```

### Actual solution:
Without making any of the above changes I now got a different warning though:
```
/usr/bin/ld: warning: libssl.so.1.0.0, needed by /media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32/libpython2.7.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /media/psf/Home/Documents/Software/Buildings-git/Buildings/Resources/Library/linux32/libpython2.7.so, not found (try using -rpath or -rpath-link)
```
It seems I did not have the 32 bit version of libssl, which was solved by:
```
sudo apt-get install libssl-dev:i386
```

Now translation works, but I get
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdat
...(message truncated)
```
when simulating.

This is fixed by http://simulationresearch.lbl.gov/modelica/releases/v2.0.0/help/Buildings_Utilities_IO_Python27_UsersGuide.html
