### ISSUE TITLE
Python2.7 does not work on Ubuntu 16.04 64-bit

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#559]
The regression tests for the package `Buildings.Utilities.IO.Python27` fail on Ubuntu 16.04 64-bit with Dymola 2017.

The models do not translate if 32 bit code is generated, which is the default on Dymola and also used for the regression tests. If 64 bit code is generated with
```
Advanced.CompileWith64=2;
```
then the examples work.

**Comment by mwetter** [comment]
The translation error is caused because
``` bash
$ grep "not found" dslog.txt 
/usr/bin/ld: warning: libssl.so.1.0.0, needed by Buildings/Resources/Library/linux32/libpython2.7.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by Buildings/Resources/Library/linux32/libpython2.7.so, not found (try using -rpath or -rpath-link)
```
This can be fixed by running
```
$ sudo apt-get install libssl1.0.0:i386
```
Now the translation works, but the simulation fails. The reason is
``` bash
$ export LD_LIBRARY_PATH="path_to_Buildings"/Buildings/Resources/Library/linux32:/opt/dymola-2017-x86_64/bin/lib
$ ./dymosim 
dymosim started
Runtime license not available, trying to check out the Dymola Standard license instead.

... "dsin.txt" loading (dymosim input file)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```
From http://stackoverflow.com/questions/15608236/eclipse-and-google-app-engine-importerror-no-module-named-sysconfigdata-nd-u, we see that
``` bash
sudo ln -s /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py /usr/lib/python2.7/
```
fixes this problem. Now, the simulation works for
```
simulateModel("Buildings.Utilities.IO.Python27.Functions.Examples.Exchange", method="Euler", fixedstepsize=1, resultFile="Exchange");
```
but fails for
```
simulateModel("Buildings.Utilities.IO.Python27.Examples.KalmanFilter", method="dassl", resultFile="KalmanFilter");
```
The error is 
```
$ ./dymosim 
dymosim started
Runtime license not available, trying to check out the Dymola Standard license instead.

... "dsin.txt" loading (dymosim input file)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```
This should be corrected with
```
sudo pip install hashlib
```
but this fails with
```
File "hashlib.py", line 115, in <module>
        f()
    TypeError: 'frozenset' object is not callable
```
Note that `easy_install` breaks the import of many Python modules, including `import hashlib`.
Hence, for now `KalmanFilter` does not work if compiled as 32 bit.

**Comment by mwetter** [comment]
As a work-around, the regression tests for `Buildings.Utilities.IO.Python27` will be executed by compiling 64 bit code.

**Comment by mwetter** [comment]
This is now on the master.
